[package]
name = "rollup"
version = "0.0.0"
description = "Minimal CLI wrapper for the unified rollup service"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
# Kona node service and providers
kona-node-service.workspace = true
kona-providers-local.workspace = true
kona-providers-alloy.workspace = true

# Reth dependencies (using workspace versions)
reth-db-api.workspace = true
reth-db.workspace = true
reth-codecs.workspace = true

# For now, we'll use placeholder types until proper reth ExEx dependencies are available
# TODO: Add proper reth and op-reth ExEx dependencies when available

# Alloy
alloy-primitives.workspace = true
alloy-provider.workspace = true

# Async runtime
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

# Error handling
anyhow.workspace = true