[package]
name = "rollup"
version = "0.0.0"
description = "Minimal CLI wrapper for the unified rollup service"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
# Kona node service and providers
kona-node-service.workspace = true
kona-providers-local.workspace = true
kona-providers-alloy.workspace = true
kona-genesis.workspace = true
kona-rpc.workspace = true
kona-disc.workspace = true
kona-peers.workspace = true
libp2p-identity.workspace = true
k256 = "0.13"
rand = "0.8"

# Reth core dependencies for NodeBuilder API integration
reth = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-node-types = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-cli-runner = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-db-api.workspace = true
reth-db.workspace = true
reth-codecs.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types-engine.workspace = true

# Async runtime
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
futures = { workspace = true }

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

# Error handling
anyhow.workspace = true
thiserror.workspace = true
eyre.workspace = true

# Testing
tempfile = "3.8"

# Serialization
serde_json = "1.0"

# Actor coordination
tokio-util.workspace = true

# CLI configuration
kona-cli = { path = "../../crates/utilities/cli", features = ["node-config"] }
clap = { workspace = true, features = ["derive"] }
url = { workspace = true }

# Chain support
alloy-chains = { workspace = true }